Repository jenkins-x-charts/tekton, pull requests merged in 2019-03, with the labels that each got.

#22 Fix handling of long task names in pods
  tekton/values.yaml
Labels: approved, size/XS

#21 fix: lets give cluster-admin to the tekton build bot
  tekton/templates/build-bot-clusterrolebinding.yaml
  tekton/templates/build-bot-role.yaml
Labels: approved, lgtm, size/XS

#24 fix: switch to Andrew's fork which has fixes and init-containers
  tekton/values.yaml
Labels: approved, lgtm, size/S
