Repository jenkins-x-charts/tekton, pull requests merged in 2019-02, with the labels that each got.

#1 add new ConfigMap required for knative pipeline
  .gitignore
  knative-build-pipeline/templates/config-artifact-bucket.yaml
Labels: approved, size/M

#4 prefix config-logging configmap with project name to avoid clash with knative build in he same namespace
  knative-build-pipeline/templates/config-logging.yaml
  knative-build-pipeline/templates/controller.yaml
  knative-build-pipeline/templates/webhook.yaml
Labels: approved, size/XS

#5 switch logging config map back to original name
  knative-build-pipeline/templates/config-logging.yaml
  knative-build-pipeline/templates/controller.yaml
  knative-build-pipeline/templates/webhook.yaml
Labels: approved, size/XS

#7 bump build pipeline
  knative-build-pipeline/templates/controller.yaml
  knative-build-pipeline/templates/webhook.yaml
Labels: approved, size/XS

#9 Add abayer to OWNERS
  OWNERS
Labels: approved, size/XS

#11 add new roles to update statuses
  knative-build-pipeline/templates/200-clusterrole.yaml
Labels: approved, size/XS

#12 enable kubernetes subresource feature on CRDs
  knative-build-pipeline/templates/300-clustertask.yaml
  knative-build-pipeline/templates/300-pipeline.yaml
  knative-build-pipeline/templates/300-pipelinerun.yaml
  knative-build-pipeline/templates/300-resource.yaml
  knative-build-pipeline/templates/300-task.yaml
  knative-build-pipeline/templates/300-taskrun.yaml
Labels: approved, size/S

#13 rename to tekton
  knative-build-pipeline/templates/200-clusterrole.yaml
  knative-build-pipeline/templates/250-docker-secret.yaml
  knative-build-pipeline/templates/250-git-secret.yaml
  knative-build-pipeline/templates/300-clustertask.yaml
  knative-build-pipeline/templates/300-pipeline.yaml
  knative-build-pipeline/templates/300-pipelinerun.yaml
  knative-build-pipeline/templates/300-resource.yaml
  knative-build-pipeline/templates/300-task.yaml
  knative-build-pipeline/templates/300-taskrun.yaml
  knative-build-pipeline/templates/_helpers.tpl
  knative-build-pipeline/templates/controller.yaml
  knative-build-pipeline/templates/webhook.yaml
  knative-build-pipeline/values.yaml
Labels: approved, lgtm, size/M

#15 rename chart to tekton
  README.md
  tekton/Chart.yaml
  tekton/Makefile
  tekton/README.md
  tekton/templates/200-clusterrole.yaml
  tekton/templates/200-clusterrolebinding.yaml
  tekton/templates/250-docker-secret.yaml
  tekton/templates/250-git-secret.yaml
  tekton/templates/250-serviceaccount.yaml
  tekton/templates/251-bot-serviceaccount.yaml
  tekton/templates/300-clustertask.yaml
  tekton/templates/300-pipeline.yaml
  tekton/templates/300-pipelinerun.yaml
  tekton/templates/300-resource.yaml
  tekton/templates/300-task.yaml
  tekton/templates/300-taskrun.yaml
  tekton/templates/400-controller-service.yaml
  tekton/templates/400-webhook-service.yaml
  tekton/templates/NOTES.txt
  tekton/templates/_helpers.tpl
  tekton/templates/build-bot-clusterrole.yaml
  tekton/templates/build-bot-clusterrolebinding.yaml
  tekton/templates/build-bot-role.yaml
  tekton/templates/build-bot-rolebinding.yaml
  tekton/templates/config-artifact-bucket.yaml
  tekton/templates/config-entrypoint.yaml
  tekton/templates/config-logging.yaml
  tekton/templates/controller.yaml
  tekton/templates/webhook.yaml
  tekton/values.yaml
Labels: approved, lgtm, size/S

#16 rename pipeline template to tekton
  tekton/templates/200-clusterrole.yaml
  tekton/templates/200-clusterrolebinding.yaml
  tekton/templates/250-serviceaccount.yaml
  tekton/templates/400-controller-service.yaml
  tekton/templates/400-webhook-service.yaml
  tekton/templates/NOTES.txt
  tekton/templates/_helpers.tpl
  tekton/templates/controller.yaml
  tekton/templates/webhook.yaml
Labels: approved, size/M

#18 add support for listing vaults
  tekton/templates/build-bot-role.yaml
Labels: approved, size/XS

#17 Update Tekton for shorter step names
  tekton/values.yaml
Labels: size/XS

#19 fix: allow pipelines to lazily create SRs
  tekton/templates/build-bot-role.yaml
Labels: approved, size/XS
