Repository jenkins-x-charts/tekton, pull requests merged in 2019-11, with the labels that each got.

#36 feat: adding ability to specify annotations
  tekton/templates/251-bot-serviceaccount.yaml
  tekton/values.yaml
Labels: approved, lgtm, size/S

#38 feat: adding ability to specify annotations
  tekton/templates/251-bot-serviceaccount.yaml
  tekton/values.yaml
Labels: approved, lgtm, size/S

#39 Revert "feat: adding ability to specify annotations"
  tekton/templates/251-bot-serviceaccount.yaml
  tekton/values.yaml
Labels: approved, size/S

#40 chore: Add BDD test for installation of tekton chart to PR pipeline
  Makefile
  jenkins-x.yml
  jx/bdd/README.md
  jx/bdd/ci.sh
  jx/bdd/cluster.yaml
  jx/bdd/helm-requirements.yaml.template
  jx/bdd/jx-requirements.yml
  jx/bdd/parameters.yaml
Labels: approved, lgtm, size/L
