Repository jenkins-x-charts/tekton, pull requests merged in 2019-05, with the labels that each got.

#29 fix: upgrade to new port
  tekton/templates/400-webhook-service.yaml
Labels: approved, size/XS

#30 Chore: Pick up latest Tekton master in chart
  tekton/values.yaml
Labels: size/S

#31 Allow configuring the Tekton PVC size
  tekton/templates/config-artifact-pvc.yaml
  tekton/values.yaml
Labels: approved, size/S

#32 chore: Update to Tekton Pipelines v0.4.0
  tekton/values.yaml
Labels: approved, size/S
